### ISSUE TITLE
Employ new login flow and quickstart page/block

### ISSUE THREAD

**Issue by meganem** [SU-SWS/stanford_sites_helper#10]

**Comment by meganem** [comment]
http://stanford.edu/group/webservices/internal/quickstart/main.html

**Comment by jbickar** [comment]
Hosting service will do these things:
- at site creation time, create an account for the person that requested the site
- give the user the administrator role
- change it so that WebAuth is no longer a choice, but rather, is enabled by default for all site installs

WMD will do this:
- Set the WMD variable to "Hide Local Drupal Login Block" by default (this still does not prevent user 1 from logging in at /user).

Stanford Sites Helper/First Steps should do this:
- If admin (user 1) or the first account has never logged in, make the "first login" page the home page.
- From then on, the first steps / quickstart page is shown.

And from that point on, they have instructions - and motivation - to set the default first page to something else.

**Comment by jbickar** [comment]
this should be done.
